"""Controlled vocabulary mapping each triage domain to weighted evidence terms."""

from __future__ import annotations

from typing import Dict, List, Tuple

# Each entry is (term, weight). Weight >= 1.0; stronger signals have higher weight.
VOCABULARY: Dict[str, List[Tuple[str, float]]] = {
    "api": [
        ("endpoint", 1.5),
        ("500", 1.2),
        ("timeout", 1.2),
        ("response", 1.0),
        ("rest", 1.5),
        ("http", 1.3),
        ("request", 1.0),
        ("status code", 1.5),
        ("payload", 1.3),
        ("curl", 1.5),
        ("api", 2.0),
        ("rate limit", 1.8),
        ("webhook", 1.8),
        ("swagger", 1.5),
        ("graphql", 1.8),
        ("json", 1.0),
        ("route", 1.0),
        ("cors", 1.5),
    ],
    "database": [
        ("query", 1.5),
        ("migration", 1.8),
        ("deadlock", 2.0),
        ("connection pool", 2.0),
        ("sql", 1.8),
        ("index", 1.2),
        ("transaction", 1.5),
        ("schema", 1.5),
        ("table", 1.2),
        ("postgres", 2.0),
        ("mysql", 2.0),
        ("mongodb", 2.0),
        ("orm", 1.8),
        ("slow query", 2.0),
        ("database", 2.0),
        ("replication", 1.8),
        ("constraint", 1.5),
        ("row lock", 2.0),
    ],
    "frontend": [
        ("render", 1.5),
        ("css", 2.0),
        ("button", 1.5),
        ("undefined", 1.2),
        ("ui", 1.8),
        ("react", 2.0),
        ("component", 1.5),
        ("layout", 1.3),
        ("style", 1.2),
        ("browser", 1.5),
        ("javascript", 1.8),
        ("dom", 1.8),
        ("click", 1.3),
        ("modal", 1.5),
        ("page", 1.0),
        ("display", 1.2),
        ("scroll", 1.3),
        ("html", 1.8),
    ],
    "auth": [
        ("login", 1.8),
        ("token", 1.8),
        ("session", 1.8),
        ("permission", 1.8),
        ("oauth", 2.0),
        ("jwt", 2.0),
        ("password", 1.8),
        ("authentication", 2.0),
        ("authorization", 2.0),
        ("logout", 1.5),
        ("2fa", 2.0),
        ("sso", 2.0),
        ("credential", 1.8),
        ("role", 1.3),
        ("access denied", 2.0),
        ("forbidden", 1.5),
        ("403", 1.5),
        ("401", 1.5),
    ],
    "build": [
        ("compile", 2.0),
        ("dependency", 1.5),
        ("pipeline", 1.8),
        ("docker", 2.0),
        ("ci", 1.5),
        ("cd", 1.2),
        ("deploy", 1.5),
        ("build", 2.0),
        ("artifact", 1.8),
        ("gradle", 2.0),
        ("maven", 2.0),
        ("npm", 1.8),
        ("webpack", 2.0),
        ("lint", 1.5),
        ("container", 1.5),
        ("image", 1.2),
        ("test failure", 1.8),
        ("package", 1.3),
    ],
}
